name: Publish

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  if_merged:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'temurin'
          cache: maven

      - name: Build Application
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          mvn package -Drevision=$VERSION

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "target/**.jar"
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
